const randomUUID=()=>`local-${Date.now()}-${Math.random().toString(36).slice(2)}`;
import { seedRecords } from "../mock-data";
import type { DomainRecord,ListQuery,Paginated,Session,Role } from "../types";
export interface AuthProvider { login(email:string,password:string):Promise<Session>; signup(name:string,email:string,password:string):Promise<Session>; requestPasswordReset(email:string):Promise<{requestId:string,code:string}>; resetPassword(requestId:string,code:string,password:string):Promise<void>; }
export interface PaymentProvider { checkout(input:{amount:number,currency:string}):Promise<{id:string,status:"success"|"failed"}>; }
export interface NotificationProvider { send(input:{to:string,subject:string,body:string}):Promise<{id:string}>; }
type User={id:string,name:string,email:string,passwordHash:string,role:Role};
const KEY="premium-template:users:v5";
const defaults=[{id:"local-user",name:"Local User",email:"user@local.test",password:"LocalUser123!",role:"user" as Role},{id:"admin-user",name:"Local Admin",email:"admin@local.test",password:"LocalAdmin123!",role:"admin" as Role}];
async function digest(value:string){const data=new TextEncoder().encode(value);if(typeof crypto!=="undefined"&&crypto.subtle){const buf=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(buf)).map(x=>x.toString(16).padStart(2,"0")).join("")}return value}
async function loadUsers():Promise<User[]>{try{if(typeof localStorage!=="undefined"){const raw=localStorage.getItem(KEY);if(raw)return JSON.parse(raw)}}catch{}const users:User[]=[];for(const x of defaults)users.push({...x,passwordHash:await digest(x.password),password:undefined} as any);saveUsers(users);return users}
function saveUsers(users:User[]){try{if(typeof localStorage!=="undefined")localStorage.setItem(KEY,JSON.stringify(users))}catch{}}
export class LocalAuthProvider implements AuthProvider { private resets=new Map<string,{code:string,userId:string}>(); async login(email:string,password:string){const hash=await digest(password);const u=(await loadUsers()).find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.passwordHash===hash);if(!u)throw new Error("INVALID_CREDENTIALS");return {userId:u.id,email:u.email,role:u.role,accessToken:randomUUID(),expiresAt:Date.now()+3600000};} async signup(name:string,email:string,password:string){const users=await loadUsers();if(users.some(x=>x.email.toLowerCase()===email.toLowerCase()))throw new Error("EMAIL_EXISTS");const u={id:randomUUID(),name,email,passwordHash:await digest(password),role:"user" as Role};users.push(u);saveUsers(users);return {userId:u.id,email:u.email,role:u.role,accessToken:randomUUID(),expiresAt:Date.now()+3600000};} async requestPasswordReset(email:string){const u=(await loadUsers()).find(x=>x.email.toLowerCase()===email.toLowerCase());if(!u)throw new Error("EMAIL_NOT_FOUND");const requestId=randomUUID(),code=String(Math.floor(100000+Math.random()*900000));this.resets.set(requestId,{code,userId:u.id});return {requestId,code};} async resetPassword(requestId:string,code:string,password:string){const reset=this.resets.get(requestId);if(!reset||reset.code!==code)throw new Error("INVALID_CODE");const users=await loadUsers();const u=users.find(x=>x.id===reset.userId);if(!u)throw new Error("INVALID_RESET");u.passwordHash=await digest(password);saveUsers(users);this.resets.delete(requestId);} }
export class MockAuthProvider extends LocalAuthProvider {}
export class MockPaymentProvider implements PaymentProvider { async checkout(input:{amount:number,currency:string}){return {id:randomUUID(),status:(input.amount>0?"success":"failed") as "success"|"failed"};} }
export class MockNotificationProvider implements NotificationProvider { async send(){return {id:randomUUID()};} }
export class LocalRepository { private rows=[...seedRecords]; async list(q:ListQuery={}):Promise<Paginated<DomainRecord>>{const page=Math.max(1,q.page??1),size=Math.min(100,Math.max(1,q.pageSize??10));let rows=this.rows.filter(x=>!q.q||x.title.toLowerCase().includes(q.q.toLowerCase())).filter(x=>!q.status||x.status===q.status);if(q.sort==="title")rows.sort((a,b)=>a.title.localeCompare(b.title));if(q.direction==="desc")rows.reverse();const start=(page-1)*size;return {data:rows.slice(start,start+size),page,pageSize:size,total:rows.length,hasNext:start+size<rows.length};} async create(row:Omit<DomainRecord,"id"|"createdAt"|"updatedAt">){const now=new Date().toISOString();const out={...row,id:randomUUID(),createdAt:now,updatedAt:now};this.rows.unshift(out);return out;} async update(id:string,patch:Partial<DomainRecord>){const i=this.rows.findIndex(x=>x.id===id);if(i<0)throw new Error("NOT_FOUND");this.rows[i]={...this.rows[i],...patch,updatedAt:new Date().toISOString()};return this.rows[i];} async remove(id:string){this.rows=this.rows.filter(x=>x.id!==id);} }
export const localMode=true;
