import {Router} from "express";import {z} from "zod";import {EntityService} from "./service";import {JsonEntityRepository} from "../persistence/entity-repository";import {PrismaClient} from "@prisma/client";import {PrismaEntityRepository} from "./prisma-repository";import {rateLimit} from "../rate-limit";import {requireAuth,requirePermission} from "../auth-middleware";
const r=Router();const modules=["posts", "authors", "bookmarks"] as const;type ModuleKey=typeof modules[number];const moduleOk=(v:string):v is ModuleKey=>modules.includes(v as ModuleKey);const createSchema=z.object({title:z.string().min(2).max(160),status:z.enum(["draft","active","paused","archived"]).default("active"),metadata:z.record(z.unknown()).default({})});
const fileRepo=new JsonEntityRepository(process.env.LOCAL_DATA_FILE||"./data/entities.json",modules);const prisma=process.env.STORAGE_MODE==="prisma"?new PrismaClient():null;const repo=prisma?new PrismaEntityRepository(prisma):fileRepo;const service=new EntityService(repo);
const guard=(req:any,res:any,next:any)=>process.env.REQUIRE_AUTH==="true"?requireAuth(req,res,next):next();
r.get("/:module",guard,async(req,res)=>{const m=req.params.module;if(!moduleOk(m))return res.status(404).json({message:"Unknown module"});try{const data=await service.list(m,String(req.query.q||""));res.json({data,total:data.length})}catch{res.status(500).json({message:"Internal server error"})}});
r.get("/:module/:id",guard,async(req,res)=>{if(!moduleOk(req.params.module))return res.status(404).json({message:"Unknown module"});const item=await service.get(req.params.id);if(!item||item.module!==req.params.module)return res.status(404).json({message:"Not found"});res.json(item)});
r.post("/:module",guard,async(req,res)=>{if(!rateLimit(req.ip))return res.status(429).json({message:"Too many requests"});const m=req.params.module;if(!moduleOk(m))return res.status(404).json({message:"Unknown module"});const p=createSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid payload",issues:p.error.issues});try{const actor=req.user?.sub||"local-user";const v=await service.create({...p.data,module:m,ownerId:actor});res.status(201).json(v)}catch{res.status(500).json({message:"Internal server error"})}});
r.patch("/:module/:id",guard,async(req,res)=>{if(!moduleOk(req.params.module))return res.status(404).json({message:"Unknown module"});const p=createSchema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid payload",issues:p.error.issues});try{const v=await service.update(req.params.id,p.data);res.json(v)}catch(e:any){res.status(e?.message==="NOT_FOUND"?404:500).json({message:e?.message==="NOT_FOUND"?"Not found":"Internal server error"})}});
r.delete("/:module/:id",guard,async(req,res)=>{if(process.env.REQUIRE_AUTH==="true"&&!requirePermission(req,"delete"))return res.status(403).json({message:"Forbidden"});try{await service.remove(req.params.id);res.status(204).end()}catch{res.status(404).json({message:"Not found"})}});export default r;
